version: 0.2

phases:
  pre_build:
    commands:
      - npm install --force
      - npm install @nestjs/cli@latest -g
  build:
    commands:
      - npm run build
  copy_files:
    commands:
      - cp -r ./.elasticbeanstalk/config.yml ./
artifacts:
  files:
    - '**/*'