version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Installing source NPM dependencies...
      - npm install --force
      - npm install @nestjs/cli@latest -g
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
    - '!node_modules/**'
    - '!test/**'
    - 'Procfile'
    - 'dist/**'
